import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { open_sans } from '@/components/fonts'
import Header from '@/components/header/header'
import Footer from '@/components/footer/footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={open_sans.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
